# Raccolta Dati da Reddit — r/Italia, keyword: *notizie*
Raccolta tramite **Arctic Shift** (archivio pubblico Reddit per ricerca accademica).

**Obiettivo**: raccogliere **100 post** di r/Italia con "notizie" nel titolo e i **top 25 commenti** per ciascun post.

Il dataset permetterà di confrontare l'emozione espressa nel post con quella dei commenti tramite **ELIta**.
I modelli pre-addestrati (feel-it, BERT italiano) saranno usati in seguito come validazione esterna.

## Installazione dipendenze

In [1]:
# !pip install requests spacy tqdm
# !python -m spacy download it_core_news_sm

## Configurazione

In [2]:
import requests
import time
import calendar
import pandas as pd
from datetime import datetime

SUBREDDIT         = "Italia"
KEYWORD           = "notizie"
N_POSTS           = 200
COMMENTS_PER_POST = 25

OUTPUT_POSTS_CSV    = f"posts_{SUBREDDIT}_{KEYWORD}.csv"
OUTPUT_COMMENTS_CSV = f"comments_{SUBREDDIT}_{KEYWORD}.csv"

BASE_URL = "https://arctic-shift.photon-reddit.com/api"
HEADERS  = {"User-Agent": "python:elita.tesi.notizie:v1.0 (academic NLP)"}

print("Configurazione:")
print(f"  Subreddit         : r/{SUBREDDIT}")
print(f"  Keyword           : '{KEYWORD}'")
print(f"  Post da raccogliere   : {N_POSTS}")
print(f"  Commenti per post     : {COMMENTS_PER_POST}")

/Users/veronicabosso/PycharmProjects/ELIta_tesi/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

Configurazione:
  Subreddit         : r/Italia
  Keyword           : 'notizie'
  Post da raccogliere   : 200
  Commenti per post     : 25

## Test connessione API
Attenzione, con servizi intermedi come **Arctic Shift** le risposte possono variare. Se lo status è 200 OK, altrimenti se è 422 riprova dopo qualche secondo.

In [3]:
# Test 1: endpoint posts/search
resp = requests.get(f"{BASE_URL}/posts/search", headers=HEADERS, timeout=20, params={
    "subreddit": SUBREDDIT, "title": KEYWORD, "limit": 2, "after": "2025-01-01", "before": "2025-01-31"
})
print(f"[posts/search]    Status: {resp.status_code}")
if resp.status_code == 200 and resp.json().get("data"):
    p = resp.json()["data"][0]
    sample_post_id = p.get("id", "")
    print(f"  Titolo   : {p.get('title','')[:80]}")
    print(f"  Score    : {p.get('score',0)}  |  Commenti: {p.get('num_comments',0)}")
    print(f"  Post ID  : {sample_post_id}")
else:
    sample_post_id = ""
    print(f"  Errore: {resp.text[:200]}")

# Test 2: endpoint comments/search per un post specifico
if sample_post_id:
    resp2 = requests.get(f"{BASE_URL}/comments/search", headers=HEADERS, timeout=20, params={
        "link_id": sample_post_id, "limit": 3
    })
    print(f"\n[comments/search] Status: {resp2.status_code}")
    if resp2.status_code == 200 and resp2.json().get("data"):
        print(f"  Primo commento: {resp2.json()['data'][0].get('body','')[:150]}")
    else:
        print(f"  Errore: {resp2.text[:200]}")

[posts/search]    Status: 200
  Titolo   : Il Pil dell'Italia è fermo, la disoccupazione sale al 6,2% - Notizie
  Score    : 241  |  Commenti: 120
  Post ID  : 1idmjsb

[comments/search] Status: 200
  Primo commento: [removed]

## Raccolta Post
Cerchiamo i post di r/Italia con "notizie" nel **titolo** tramite `/api/posts/search`.
Finestre mensili per evitare il rate limit (stessa tecnica dei commenti).

In [4]:
def collect_posts(subreddit, keyword, target=100):
    all_posts = []

    # Finestre mensili: 2025 → 2024 → 2023 (ci fermiamo appena raggiungiamo il target)
    time_windows = []
    for year in [2025, 2024, 2023]:
        max_month = 5 if year == 2025 else 12
        for month in range(max_month, 0, -1):
            last_day = calendar.monthrange(year, month)[1]
            time_windows.append((f"{year}-{month:02d}-01", f"{year}-{month:02d}-{last_day}", f"{year}-{month:02d}"))

    for after, before, label in time_windows:
        if len(all_posts) >= target:
            break

        params = {"subreddit": subreddit, "title": keyword, "limit": 25, "after": after, "before": before}
        last_utc = None

        while len(all_posts) < target:
            if last_utc:
                params["before"] = last_utc
            try:
                resp = requests.get(f"{BASE_URL}/posts/search", headers=HEADERS, params=params, timeout=30)
                if resp.status_code == 422:
                    break
                resp.raise_for_status()
                items = resp.json().get("data", [])
            except Exception as e:
                print(f"  Errore {label}: {e}")
                break

            if not items:
                break

            for p in items:
                if len(all_posts) >= target:
                    break
                title = p.get("title", "").strip()
                if not title:
                    continue
                selftext = p.get("selftext", "").strip()
                if selftext in ("[removed]", "[deleted]"):
                    selftext = ""
                ts = float(p.get("created_utc", 0))
                all_posts.append({
                    "post_id"     : p.get("id", ""),
                    "title"       : title,
                    "selftext"    : selftext,
                    "author"      : p.get("author", ""),
                    "timestamp"   : datetime.utcfromtimestamp(ts).isoformat(),
                    "score"       : p.get("score", 0),
                    "num_comments": p.get("num_comments", 0),
                    "url"         : "https://reddit.com" + p.get("permalink", "") if p.get("permalink") else "",
                })

            oldest_utc = min(float(p.get("created_utc", 0)) for p in items)
            last_utc   = datetime.utcfromtimestamp(oldest_utc).strftime("%Y-%m-%dT%H:%M:%S")
            if len(items) < 25:
                break
            time.sleep(1)

        print(f"  {label}: {len(all_posts)} post totali", end="\r")
        time.sleep(1.5)

    print(f"\nPost raccolti: {len(all_posts)}")
    return all_posts

posts = collect_posts(SUBREDDIT, KEYWORD, target=N_POSTS)
df_posts = pd.DataFrame(posts)
print(df_posts[["post_id", "title", "score", "num_comments", "timestamp"]].head(5))

  2023-11: 200 post totali
Post raccolti: 200
   post_id                                              title  score  \
0  1kwlwc6                Quanto odio quei siti di notizie...     31
1  1kuc88y                          Notizie da un macchinista      1
2  1kq6axq  Secondo voi con l'aumento dell'immigrazione cl...      0
3  1kna8hg  Un sms della cugina di Chiara Poggi: 'Mi sa ch...     48
4  1kn9cp6  Su Reddit ma anche sui quotidiani spesso vedo ...    126

   num_comments            timestamp
0            24  2025-05-27T12:23:55
1             1  2025-05-24T13:57:01
2            26  2025-05-19T08:07:57
3             9  2025-05-15T14:54:26
4            57  2025-05-15T14:17:43

## Raccolta Commenti per Post
Per ogni post, raccogliamo fino a **100 commenti** dall'API (ordinati per `created_utc` discendente),
poi li ordiniamo per **score decrescente** lato Python e teniamo i **top 25**.

Questo garantisce che i commenti selezionati siano quelli più apprezzati dalla community,
che rappresentano meglio la reazione collettiva al post.

In [9]:
### ATTENZIONE non esuire sta cella se non vuoi perdere 5 min di vita
def collect_comments_for_posts(df_posts, n_comments=25, fetch_limit=100):
    """
    Per ogni post:
      - recupera fino a `fetch_limit` commenti dall'API paginando correttamente
      - ordina per score decrescente
      - tiene i top `n_comments`
    """
    all_comments = []

    for i, row in df_posts.iterrows():
        post_id  = row["post_id"]
        raw_items = []
        last_utc  = None

        # Paginazione corretta: continua finché non raggiungiamo fetch_limit
        # o l'API non ha più risultati
        while len(raw_items) < fetch_limit:
            params = {"link_id": post_id, "limit": 100}
            if last_utc:
                params["before"] = last_utc

            try:
                resp = requests.get(f"{BASE_URL}/comments/search", headers=HEADERS,
                                    params=params, timeout=30)
                if resp.status_code != 200:
                    break
                items = resp.json().get("data", [])
            except Exception as e:
                print(f"  Errore post {post_id}: {e}")
                break

            if not items:
                break

            raw_items.extend(items)

            # Aggiorna il cursore PRIMA di decidere se continuare
            oldest_utc = min(float(c.get("created_utc", 0)) for c in items)
            last_utc   = datetime.utcfromtimestamp(oldest_utc).strftime("%Y-%m-%dT%H:%M:%S")

            # Se l'API ha restituito meno di 100, non ci sono altre pagine
            if len(items) < 100:
                break

            time.sleep(0.3)

        # Filtra rimossi/troppo corti, ordina per score, tieni i top n
        valid = [
            c for c in raw_items
            if c.get("body", "").strip() not in ("", "[deleted]", "[removed]")
            and len(c.get("body", "").strip()) >= 10
        ]
        top = sorted(valid, key=lambda c: c.get("score", 0), reverse=True)[:n_comments]

        for rank, c in enumerate(top, start=1):
            ts = float(c.get("created_utc", 0))
            all_comments.append({
                "comment_id"   : c.get("id", ""),
                "post_id"      : post_id,
                "rank_by_score": rank,
                "comment_text" : c.get("body", "").strip(),
                "author"       : c.get("author", ""),
                "timestamp"    : datetime.utcfromtimestamp(ts).isoformat(),
                "score"        : c.get("score", 0),
                "permalink"    : "https://reddit.com" + c.get("permalink", "")
                                  if c.get("permalink") else "",
            })

        print(f"  [{i+1:3d}/{len(df_posts)}] {post_id}: "
              f"{len(raw_items)} recuperati → {len(valid)} validi → top {len(top)}")
        time.sleep(0.8)

    print(f"\nCommenti totali: {len(all_comments)}")
    return all_comments

comments = collect_comments_for_posts(df_posts, n_comments=COMMENTS_PER_POST, fetch_limit=100)
df_comments = pd.DataFrame(comments)
print(df_comments[["comment_id", "post_id", "rank_by_score", "score", "comment_text"]].head(8))

  [  1/200] 1kwlwc6: 26 recuperati → 25 validi → top 25
  [  2/200] 1kuc88y: 1 recuperati → 1 validi → top 1
  [  3/200] 1kq6axq: 33 recuperati → 31 validi → top 25
  [  4/200] 1kna8hg: 10 recuperati → 10 validi → top 10
  [  5/200] 1kn9cp6: 59 recuperati → 58 validi → top 25
  [  6/200] 1kjv1dn: 1 recuperati → 1 validi → top 1
  [  7/200] 1khu4t1: 0 recuperati → 0 validi → top 0
  [  8/200] 1khu16n: 0 recuperati → 0 validi → top 0
  [  9/200] 1khu0wh: 0 recuperati → 0 validi → top 0
  [ 10/200] 1khu0sz: 0 recuperati → 0 validi → top 0
  [ 11/200] 1kem3wd: 1 recuperati → 1 validi → top 1
  [ 12/200] 1ke1jvk: 1 recuperati → 1 validi → top 1
  [ 13/200] 1kd66x8: 5 recuperati → 4 validi → top 4
  [ 14/200] 1kczbl2: 5 recuperati → 5 validi → top 5
  [ 15/200] 1kcz8yh: 56 recuperati → 54 validi → top 25
  [ 16/200] 1kc8tre: 6 recuperati → 6 validi → top 6
  [ 17/200] 1ka1u9n: 3 recuperati → 3 validi → top 3
  [ 18/200] 1k9s902: 1 recuperati → 1 validi → top 1
  [ 19/200] 1k7hecq: 3 recuperati → 3 validi → top 3
  [ 20/200] 1k6qw5m: 7 recuperati → 7 validi → top 7
  [ 21/200] 1k3omsy: 3 recuperati → 3 validi → top 3
  [ 22/200] 1jqe2zq: 100 recuperati → 97 validi → top 25
  [ 23/200] 1jpbxj3: 12 recuperati → 11 validi → top 11
  [ 24/200] 1jcyj9b: 25 recuperati → 25 validi → top 25
  [ 25/200] 1j8pvoo: 8 recuperati → 8 validi → top 8
  [ 26/200] 1j745ih: 49 recuperati → 47 validi → top 25
  [ 27/200] 1j6p2kp: 48 recuperati → 48 validi → top 25
  [ 28/200] 1j4vdq2: 0 recuperati → 0 validi → top 0
  [ 29/200] 1j3anb9: 0 recuperati → 0 validi → top 0
  [ 30/200] 1j2y8s0: 100 recuperati → 99 validi → top 25
  [ 31/200] 1j13txr: 64 recuperati → 62 validi → top 25
  [ 32/200] 1izexqw: 1 recuperati → 1 validi → top 1
  Errore post 1iwwsib: HTTPSConnectionPool(host='arctic-shift.photon-reddit.com', port=443): Read timed out. (read timeout=30)
  [ 33/200] 1iwwsib: 0 recuperati → 0 validi → top 0
  [ 34/200] 1ivpcav: 69 recuperati → 68 validi → top 25
  [ 35/200] 1iuvzbe: 9 recuperati → 8 validi → top 8
  [ 36/200] 1it0qcw: 0 recuperati → 0 validi → top 0
  [ 37/200] 1isem4t: 100 recuperati → 96 validi → top 25
  [ 38/200] 1is4kvh: 100 recuperati → 97 validi → top 25
  [ 39/200] 1ijcj7q: 4 recuperati → 3 validi → top 3
  [ 40/200] 1iik2v6: 4 recuperati → 4 validi → top 4
  [ 41/200] 1iiehj9: 0 recuperati → 0 validi → top 0
  [ 42/200] 1ihiz9c: 41 recuperati → 38 validi → top 25
  [ 43/200] 1idmjsb: 100 recuperati → 98 validi → top 25
  [ 44/200] 1ibjb4n: 0 recuperati → 0 validi → top 0
  [ 45/200] 1i91z6n: 22 recuperati → 21 validi → top 21
  [ 46/200] 1i6uz79: 1 recuperati → 1 validi → top 1
  [ 47/200] 1hwcyp6: 0 recuperati → 0 validi → top 0
  [ 48/200] 1hndolp: 98 recuperati → 97 validi → top 25
  [ 49/200] 1hl10pv: 2 recuperati → 2 validi → top 2
  [ 50/200] 1hiryze: 71 recuperati → 71 validi → top 25
  [ 51/200] 1hcejfy: 0 recuperati → 0 validi → top 0
  [ 52/200] 1hax8qf: 17 recuperati → 17 validi → top 17
  [ 53/200] 1h8qq5x: 0 recuperati → 0 validi → top 0
  [ 54/200] 1h8d2en: 55 recuperati → 55 validi → top 25
  [ 55/200] 1gvq43y: 100 recuperati → 98 validi → top 25
  [ 56/200] 1gu0s12: 2 recuperati → 2 validi → top 2
  [ 57/200] 1gsn2ej: 40 recuperati → 38 validi → top 25
  [ 58/200] 1grbwzo: 18 recuperati → 15 validi → top 15
  [ 59/200] 1gjetvh: 62 recuperati → 62 validi → top 25
  [ 60/200] 1gf0loe: 11 recuperati → 11 validi → top 11
  [ 61/200] 1g9ald0: 1 recuperati → 1 validi → top 1
  [ 62/200] 1g8xxps: 15 recuperati → 15 validi → top 15
  [ 63/200] 1g4vnt8: 4 recuperati → 4 validi → top 4
  [ 64/200] 1g3kh7j: 14 recuperati → 14 validi → top 14
  [ 65/200] 1g0hg5b: 1 recuperati → 1 validi → top 1
  [ 66/200] 1g0ey50: 12 recuperati → 11 validi → top 11
  [ 67/200] 1fvuvoe: 38 recuperati → 37 validi → top 25
  [ 68/200] 1fsd383: 45 recuperati → 39 validi → top 25
  [ 69/200] 1frl8qs: 17 recuperati → 17 validi → top 17
  [ 70/200] 1fq5kqj: 1 recuperati → 1 validi → top 1
  [ 71/200] 1fpw7z7: 0 recuperati → 0 validi → top 0
  [ 72/200] 1fmtbpe: 7 recuperati → 7 validi → top 7
  [ 73/200] 1fj235i: 3 recuperati → 3 validi → top 3
  [ 74/200] 1fj1dyw: 100 recuperati → 99 validi → top 25
  [ 75/200] 1ff3mbv: 20 recuperati → 20 validi → top 20
  [ 76/200] 1fe4tur: 0 recuperati → 0 validi → top 0
  [ 77/200] 1fb0v9h: 3 recuperati → 3 validi → top 3
  [ 78/200] 1f90v1h: 3 recuperati → 3 validi → top 3
  [ 79/200] 1f8rmiz: 41 recuperati → 38 validi → top 25
  [ 80/200] 1f73lup: 0 recuperati → 0 validi → top 0
  [ 81/200] 1f73l9b: 0 recuperati → 0 validi → top 0
  [ 82/200] 1f4qb0n: 13 recuperati → 13 validi → top 13
  [ 83/200] 1evxlfp: 16 recuperati → 16 validi → top 16
  [ 84/200] 1eucise: 3 recuperati → 3 validi → top 3
  [ 85/200] 1es7vs0: 0 recuperati → 0 validi → top 0
  [ 86/200] 1eht5ov: 3 recuperati → 3 validi → top 3
  [ 87/200] 1ehbcj7: 100 recuperati → 100 validi → top 25
  [ 88/200] 1eeu93u: 13 recuperati → 13 validi → top 13
  [ 89/200] 1e8x3us: 14 recuperati → 14 validi → top 14
  [ 90/200] 1e4lf9i: 100 recuperati → 98 validi → top 25
  [ 91/200] 1dzup0d: 8 recuperati → 8 validi → top 8
  [ 92/200] 1dy3xpt: 22 recuperati → 22 validi → top 22
  [ 93/200] 1dxrowz: 3 recuperati → 3 validi → top 3
  [ 94/200] 1dxohfx: 73 recuperati → 72 validi → top 25
  [ 95/200] 1dwvfqm: 42 recuperati → 42 validi → top 25
  [ 96/200] 1dvujmr: 14 recuperati → 13 validi → top 13
  [ 97/200] 1dr7369: 2 recuperati → 2 validi → top 2
  [ 98/200] 1dqgim5: 53 recuperati → 52 validi → top 25
  [ 99/200] 1ddjzdd: 59 recuperati → 55 validi → top 25
  [100/200] 1dahedk: 0 recuperati → 0 validi → top 0
  [101/200] 1d3cpwk: 51 recuperati → 50 validi → top 25
  [102/200] 1d1obvw: 15 recuperati → 15 validi → top 15
  [103/200] 1cynkba: 16 recuperati → 16 validi → top 16
  [104/200] 1ctarkf: 20 recuperati → 18 validi → top 18
  [105/200] 1cqus6n: 8 recuperati → 8 validi → top 8
  [106/200] 1cpdn0i: 38 recuperati → 36 validi → top 25
  [107/200] 1covdte: 26 recuperati → 26 validi → top 25
  [108/200] 1cm9ml0: 100 recuperati → 99 validi → top 25
  [109/200] 1cklo0k: 71 recuperati → 67 validi → top 25
  [110/200] 1ck64ng: 100 recuperati → 96 validi → top 25
  [111/200] 1cehqlf: 4 recuperati → 4 validi → top 4
  [112/200] 1cabot7: 100 recuperati → 82 validi → top 25
  [113/200] 1c6inaz: 40 recuperati → 40 validi → top 25
  [114/200] 1c5o2iy: 1 recuperati → 1 validi → top 1
  [115/200] 1c21hkb: 0 recuperati → 0 validi → top 0
  [116/200] 1c0refq: 62 recuperati → 60 validi → top 25
  [117/200] 1bwjbi5: 0 recuperati → 0 validi → top 0
  [118/200] 1bpf2h1: 7 recuperati → 7 validi → top 7
  [119/200] 1bf8n6u: 0 recuperati → 0 validi → top 0
  [120/200] 1begvjh: 9 recuperati → 9 validi → top 9
  [121/200] 1bcya8k: 14 recuperati → 14 validi → top 14
  [122/200] 1bbapib: 0 recuperati → 0 validi → top 0
  [123/200] 1bbaocw: 0 recuperati → 0 validi → top 0
  [124/200] 1bb5490: 100 recuperati → 98 validi → top 25
  [125/200] 1b8zoar: 47 recuperati → 46 validi → top 25
  [126/200] 1b3pa07: 100 recuperati → 95 validi → top 25
  [127/200] 1b2726j: 8 recuperati → 8 validi → top 8
  [128/200] 1b1651l: 4 recuperati → 4 validi → top 4
  [129/200] 1b0sosj: 2 recuperati → 1 validi → top 1
  [130/200] 1b0cdwx: 25 recuperati → 25 validi → top 25
  [131/200] 1ayoxfg: 22 recuperati → 21 validi → top 21
  [132/200] 1axxrfw: 15 recuperati → 12 validi → top 12
  [133/200] 1ax2yw1: 11 recuperati → 10 validi → top 10
  [134/200] 1aws5j8: 45 recuperati → 42 validi → top 25
  [135/200] 1awkcgy: 0 recuperati → 0 validi → top 0
  [136/200] 1awbl91: 2 recuperati → 1 validi → top 1
  [137/200] 1aw63lh: 34 recuperati → 34 validi → top 25
  [138/200] 1avbxxr: 23 recuperati → 22 validi → top 22
  [139/200] 1av0h06: 47 recuperati → 46 validi → top 25
  [140/200] 1ascu97: 1 recuperati → 1 validi → top 1
  [141/200] 1as40ze: 17 recuperati → 17 validi → top 17
  [142/200] 1arjbw8: 52 recuperati → 49 validi → top 25
  [143/200] 1ara7ty: 10 recuperati → 10 validi → top 10
  [144/200] 1aqnwy2: 0 recuperati → 0 validi → top 0
  [145/200] 1aqi91k: 0 recuperati → 0 validi → top 0
  [146/200] 1ap5p7i: 27 recuperati → 24 validi → top 24
  [147/200] 1aou84w: 49 recuperati → 48 validi → top 25
  [148/200] 1ant1dc: 0 recuperati → 0 validi → top 0
  [149/200] 1ankd2s: 17 recuperati → 17 validi → top 17
  [150/200] 1ank467: 1 recuperati → 1 validi → top 1
  [151/200] 1ammjqg: 100 recuperati → 97 validi → top 25
  [152/200] 1alzpuo: 19 recuperati → 19 validi → top 19
  [153/200] 1als61l: 76 recuperati → 73 validi → top 25
  [154/200] 1alq00u: 100 recuperati → 98 validi → top 25
  [155/200] 1ak3o2u: 9 recuperati → 9 validi → top 9
  [156/200] 1ac5iz8: 0 recuperati → 0 validi → top 0
  [157/200] 1abdrgp: 4 recuperati → 4 validi → top 4
  [158/200] 1abc7lc: 7 recuperati → 7 validi → top 7
  [159/200] 19fbiy3: 0 recuperati → 0 validi → top 0
  [160/200] 19eaxln: 4 recuperati → 4 validi → top 4
  [161/200] 19dk27x: 5 recuperati → 5 validi → top 5
  [162/200] 19di9l7: 27 recuperati → 26 validi → top 25
  [163/200] 19bcc4u: 9 recuperati → 9 validi → top 9
  [164/200] 19acv7l: 1 recuperati → 1 validi → top 1
  [165/200] 19a19xz: 0 recuperati → 0 validi → top 0
  [166/200] 199mclh: 43 recuperati → 41 validi → top 25
  [167/200] 198ykw6: 2 recuperati → 1 validi → top 1
  [168/200] 198r5xr: 3 recuperati → 3 validi → top 3
  [169/200] 195hzfg: 0 recuperati → 0 validi → top 0
  [170/200] 193vzzv: 11 recuperati → 10 validi → top 10
  [171/200] 1932u3m: 5 recuperati → 4 validi → top 4
  [172/200] 192mp8h: 0 recuperati → 0 validi → top 0
  [173/200] 192jbnt: 9 recuperati → 9 validi → top 9
  [174/200] 190vonr: 11 recuperati → 10 validi → top 10
  [175/200] 18ym87w: 0 recuperati → 0 validi → top 0
  [176/200] 18wr2mb: 57 recuperati → 55 validi → top 25
  [177/200] 18vutif: 36 recuperati → 35 validi → top 25
  [178/200] 18trza3: 0 recuperati → 0 validi → top 0
  [179/200] 18srt8j: 8 recuperati → 7 validi → top 7
  [180/200] 18sogtl: 0 recuperati → 0 validi → top 0
  [181/200] 18s48js: 2 recuperati → 2 validi → top 2
  [182/200] 18nlo1m: 48 recuperati → 46 validi → top 25
  [183/200] 18mu677: 2 recuperati → 2 validi → top 2
  [184/200] 18msect: 38 recuperati → 38 validi → top 25
  [185/200] 18m9u2c: 1 recuperati → 1 validi → top 1
  [186/200] 18kjlc2: 1 recuperati → 1 validi → top 1
  [187/200] 18jqe9s: 30 recuperati → 30 validi → top 25
  [188/200] 18ea9no: 0 recuperati → 0 validi → top 0
  [189/200] 18ea9ib: 2 recuperati → 2 validi → top 2
  [190/200] 18crdmm: 7 recuperati → 6 validi → top 6
  [191/200] 18cbbrl: 6 recuperati → 6 validi → top 6
  [192/200] 18bd7eq: 9 recuperati → 9 validi → top 9
  [193/200] 18ahy4u: 45 recuperati → 44 validi → top 25
  [194/200] 189uz8o: 47 recuperati → 44 validi → top 25
  [195/200] 189s33i: 72 recuperati → 71 validi → top 25
  [196/200] 185ybf7: 1 recuperati → 1 validi → top 1
  [197/200] 184zmfq: 51 recuperati → 50 validi → top 25
  [198/200] 184gosu: 7 recuperati → 7 validi → top 7
  [199/200] 1817buy: 6 recuperati → 5 validi → top 5
  [200/200] 17swgyf: 0 recuperati → 0 validi → top 0

Commenti totali: 2320
  comment_id  post_id  rank_by_score  score  \
0    mui73c3  1kwlwc6              1     16
1    muia2oi  1kwlwc6              2     11
2    mui7csr  1kwlwc6              3      6
3    muimms8  1kwlwc6              4      4
4    muieq6e  1kwlwc6              5      4
5    muie9dq  1kwlwc6              6      4
6    muibb6m  1kwlwc6              7      4
7    muilbay  1kwlwc6              8      3

                                        comment_text
0                                 Easy, non li apro.
1  Più facile: usa ublok origin o Brave Browser e...
2          Mica lo sai prima che non te li mostrano!
3  Lo fanno perché il mio commento può essere int...
4  I cookie ormai li rifiuto sempre e comunque \n...
5  No puoi proprio bloccarli dal principio sia co...
6  Apro in modalità in incognito, accetto i cooki...
7  Non capisco perché ti downvotano...a giudicare...

## Salvataggio CSV
Quattro file:
- **`posts_Italia_notizie.csv`** — un post per riga
- **`comments_Italia_notizie.csv`** — un commento per riga, con `post_id` come chiave di join
- **`merged_Italia_notizie.csv`** — ogni commento affiancato ai dati del post di origine
- **`corpus_Italia_notizie.csv`** — long format: una riga per documento (post o commento), colonna `type` per distinguerli, `text` come testo da analizzare con ELIta

In [10]:
# Salva posts
df_posts.to_csv(OUTPUT_POSTS_CSV, index=False, encoding="utf-8-sig")
print(f"Post salvati    : {len(df_posts)} righe → '{OUTPUT_POSTS_CSV}'")

# Salva commenti
df_comments.to_csv(OUTPUT_COMMENTS_CSV, index=False, encoding="utf-8-sig")
print(f"Commenti salvati: {len(df_comments)} righe → '{OUTPUT_COMMENTS_CSV}'")

# Merged: ogni commento affiancato ai dati del suo post (left join)
OUTPUT_MERGED_CSV = f"merged_{SUBREDDIT}_{KEYWORD}.csv"
df_merged = df_comments.merge(
    df_posts[["post_id", "title", "selftext", "score", "num_comments", "timestamp", "url"]],
    on="post_id",
    how="left",
    suffixes=("_comment", "_post")
)
df_merged.to_csv(OUTPUT_MERGED_CSV, index=False, encoding="utf-8-sig")
print(f"Merged salvato  : {len(df_merged)} righe → '{OUTPUT_MERGED_CSV}'")

# Corpus long-format: una riga per documento (post o commento)
OUTPUT_CORPUS_CSV = f"corpus_{SUBREDDIT}_{KEYWORD}.csv"

posts_long = df_posts.assign(
    type="post",
    doc_id=df_posts["post_id"],
    text=df_posts.apply(
        lambda r: (r["title"] + "\n" + r["selftext"]).strip() if r["selftext"] else r["title"],
        axis=1
    ),
    rank_by_score=None,
)[["doc_id", "post_id", "type", "text", "author", "timestamp", "score", "rank_by_score"]]

comments_long = df_comments.rename(columns={"comment_id": "doc_id", "comment_text": "text"}) \
    .assign(type="comment")[["doc_id", "post_id", "type", "text", "author", "timestamp", "score", "rank_by_score"]]

df_corpus = pd.concat([posts_long, comments_long], ignore_index=True)
df_corpus.to_csv(OUTPUT_CORPUS_CSV, index=False, encoding="utf-8-sig")
print(f"Corpus salvato  : {len(df_corpus)} righe → '{OUTPUT_CORPUS_CSV}'")
print(f"  post: {(df_corpus['type']=='post').sum()}  |  commenti: {(df_corpus['type']=='comment').sum()}")

# Anteprima
print("\n--- Corpus: prime 2 righe (post) ---")
display(df_corpus[["doc_id", "post_id", "type", "text", "score"]].head(2))
print("\n--- Corpus: ultimi 2 righe (commenti) ---")
display(df_corpus[["doc_id", "post_id", "type", "text", "score"]].tail(2))

Post salvati    : 200 righe → 'posts_Italia_notizie.csv'
Commenti salvati: 2320 righe → 'comments_Italia_notizie.csv'
Merged salvato  : 2320 righe → 'merged_Italia_notizie.csv'
Corpus salvato  : 2520 righe → 'corpus_Italia_notizie.csv'
  post: 200  |  commenti: 2320

--- Corpus: prime 2 righe (post) ---

,doc_id,post_id,type,text,score
0,1kwlwc6,1kwlwc6,post,Quanto odio quei siti di notizie...\n...in cui...,31
1,1kuc88y,1kuc88y,post,Notizie da un macchinista\nSe nei prossimi ved...,1

--- Corpus: ultimi 2 righe (commenti) ---

,doc_id,post_id,type,text,score
2518,kaapuhv,1817buy,comment,Ciao sono in Botswana e sto mangiando una pizz...,4
2519,kaan9yn,1817buy,comment,"Strano però, ma questi non erano quelli ossess...",2

## Statistiche del corpus

In [11]:
import plotly.express as px

print("=" * 50)
print("STATISTICHE CORPUS")
print("=" * 50)
print(f"Post totali              : {len(df_posts)}")
print(f"  - con testo (selftext) : {(df_posts['selftext'] != '').sum()}")
print(f"  - solo link            : {(df_posts['selftext'] == '').sum()}")
print(f"Commenti totali          : {len(df_comments)}")
print(f"Media commenti per post  : {len(df_comments)/len(df_posts):.1f}")
print(f"Autori unici (post)      : {df_posts['author'].nunique()}")
print(f"Autori unici (commenti)  : {df_comments['author'].nunique()}")
print(f"Periodo post             : {df_posts['timestamp'].min()[:10]} → {df_posts['timestamp'].max()[:10]}")

# Post per mese
df_posts["mese"] = df_posts["timestamp"].str[:7]
fig1 = px.bar(df_posts["mese"].value_counts().sort_index().reset_index(),
              x="mese", y="count", title="Post per mese",
              labels={"mese": "Mese", "count": "Post"})
fig1.show()

# Distribuzione commenti per post
commenti_per_post = df_comments.groupby("post_id").size().reset_index(name="n_commenti")
fig2 = px.histogram(commenti_per_post, x="n_commenti", nbins=26,
                    title="Distribuzione commenti raccolti per post",
                    labels={"n_commenti": "Commenti raccolti", "count": "Post"})
fig2.show()

# Top 10 post per score
print("\nTop 10 post per score:")
display(df_posts.nlargest(10, "score")[["title", "score", "num_comments", "timestamp"]])

==================================================
STATISTICHE CORPUS
==================================================
Post totali              : 200
  - con testo (selftext) : 44
  - solo link            : 156
Commenti totali          : 2320
Media commenti per post  : 11.6
Autori unici (post)      : 112
Autori unici (commenti)  : 1247
Periodo post             : 2023-11-11 → 2025-05-27

Top 10 post per score:

,title,score,num_comments,timestamp
111,"basta politica e brutte notizie, guardate sta ...",912,138,2024-04-22T14:06:33
152,Classe va a vedere uno spettacolo sull'inclusi...,344,72,2024-02-08T09:49:08
107,Buone notizie Telepass decide di modificare og...,314,153,2024-05-07T11:29:03
14,Notizie top tier,262,54,2025-05-02T12:03:46
42,"Il Pil dell'Italia è fermo, la disoccupazione ...",241,120,2025-01-30T13:07:36
23,Le grandi notizie di Repubblica,211,25,2025-03-16T23:13:06
153,"Preside preso a pugni, le sue parole: ""I genit...",174,175,2024-02-08T07:13:03
53,Studenti italiani campioni europei dei compiti...,171,50,2024-12-06T22:04:26
21,"Nordio: ""Alcune etnie hanno sensibilità divers...",170,318,2025-04-03T09:37:58
150,Gli alunni non sanno più scrivere in corsivo. ...,167,376,2024-02-09T11:59:49

## Tokenizzazione, Lemmatizzazione e POS-tagging

Utilizziamo il modello italiano `it_core_news_sm` di spaCy per analizzare tutti i documenti del corpus (post e commenti). Per ogni token estraiamo:
- `token`: testo originale
- `lemma`: forma base in minuscolo
- `pos`: parte del discorso (NOUN, VERB, ADJ, …)
- `is_adj`: flag booleano se è un aggettivo

Filtriamo spazi e punteggiatura. L'identificatore è `doc_id` (che vale sia per post che commenti).

Salviamo il risultato in `tokens_Italia_notizie.csv`.

In [12]:
import spacy
import emoji as emoji_lib
from tqdm.auto import tqdm

nlp = spacy.load("it_core_news_sm")

def process_text(text):
    doc = nlp(str(text))
    tokens = []
    for token in doc:
        if token.is_space or token.is_punct:
            continue
        # Forza POS uniforme per tutte le emoji, indipendentemente da spaCy
        pos = "EMOJI" if emoji_lib.emoji_count(token.text) > 0 else token.pos_
        tokens.append({
            "token" : token.text,
            "lemma" : token.lemma_.lower(),
            "pos"   : pos,
            "is_adj": pos == "ADJ",
        })
    return tokens

# Test su un documento di esempio (primo post)
esempio_row = df_corpus.iloc[0]
print(f"Tipo: {esempio_row['type']}  |  doc_id: {esempio_row['doc_id']}")
print(f"Testo:\n{esempio_row['text'][:200]}\n")
print("Analisi (primi 15 token):")
for t in process_text(esempio_row["text"])[:15]:
    flag = " <- ADJ" if t["is_adj"] else ""
    print(f"  {t['token']:20s} | {t['lemma']:20s} | {t['pos']}{flag}")

print(f"\nProcessamento di {len(df_corpus)} documenti con spaCy...")

all_tokens = []
for _, row in tqdm(df_corpus.iterrows(), total=len(df_corpus)):
    for t in process_text(row["text"]):
        all_tokens.append({"doc_id": row["doc_id"], **t})

df_tokens = pd.DataFrame(all_tokens)
df_adj    = df_tokens[df_tokens["is_adj"]]
df_emoji  = df_tokens[df_tokens["pos"] == "EMOJI"]

print(f"\nToken totali     : {len(df_tokens)}")
print(f"Aggettivi trovati: {len(df_adj)}")
print(f"Emoji trovate    : {len(df_emoji)} ({df_emoji['lemma'].nunique()} distinte)")

tokens_file = f"tokens_{SUBREDDIT}_{KEYWORD}.csv"
df_tokens.to_csv(tokens_file, index=False, encoding="utf-8-sig")
print(f"\nToken salvati in '{tokens_file}'")

Tipo: post  |  doc_id: 1kwlwc6
Testo:
Quanto odio quei siti di notizie...
...in cui ti chiedono di accettare 200 biscotti 🍪 🍪 per poter visualizzare l'articolo e non appena li accetti ti comunicano che comunque è a pagamento quindi sticaz

Analisi (primi 15 token):
  Quanto               | quanto               | ADV
  odio                 | odiare               | VERB
  quei                 | quello               | DET
  siti                 | sito                 | NOUN
  di                   | di                   | ADP
  notizie              | notizia              | NOUN
  in                   | in                   | ADP
  cui                  | cui                  | PRON
  ti                   | ti                   | PRON
  chiedono             | chiedere             | VERB
  di                   | di                   | ADP
  accettare            | accettare            | VERB
  200                  | 200                  | NUM
  biscotti             | biscotto             | NOUN
  🍪                    | 🍪                    | EMOJI

Processamento di 2520 documenti con spaCy...

100%|██████████| 2520/2520 [00:18<00:00, 135.39it/s]

Token totali     : 84867
Aggettivi trovati: 5502
Emoji trovate    : 112 (56 distinte)

Token salvati in 'tokens_Italia_notizie.csv'